# Todo: 1. 上电时确认串口设备路径是否正确，若不正确则修改为正确的路径。
send_port: /dev/ttyACM0
receive_port: /dev/ttyACM0

yolo_model_path: /home/nvidia/NJU-algorithm/vision_task/armor_task/models/best.engine
video_path : /home/nvidia/NJU-algorithm/vision_task/armor_task/assets/circular.avi
config_path : /home/nvidia/NJU-algorithm/vision_task/armor_task/config/camera1.yaml
bullet_speed : 20
