yolo_model_path: /home/nvidia/NJU_RMVision/armor_task/models/best.engine
video_path : /home/nvidia/NJU_RMVision/armor_task/assets/camera_record.avi
config_path : /home/nvidia/NJU_RMVision/armor_task/config/camera1.yaml
bullet_speed : 16.7
