/decision_node:
  ros__parameters:
    nav_namespace: ""
    waypoints_path: "/home/nvidia/NJU-algorithm/decision_task/config/waypoint/waypoints_simple.json"
    decisions_path: "/home/nvidia/NJU-algorithm/decision_task/config/decision/decisions.json"
    map_path: "/home/nvidia/NJU-algorithm/decision_task/config/RMUL.png"
    distance_thr: 1.0
    seek_thr: 5.0
    real_width: 12.0
    real_height: 8.0
    step_distance: 0.1
    car_seek_fov: 70.0
    initial_pose:
      x: -2.0
      y: -3.0
      theta: 0.0
